# SPDX-License-Identifier: LicenseRef-Leo-Y-Zhang-Proprietary
"""The model/scenario editor: a group tree (the six TritonConfig sub-configs +
the scenario) on the left, and a properties panel on the right that repopulates
on selection. Field widgets are generated by introspecting the dataclass; every
edit goes through ``Session.set_field`` (validated + undoable). All fields are
shown grouped (no Default/Advanced verbosity toggle — the sole user knows them).
"""
from __future__ import annotations

from dataclasses import fields

from PySide6.QtCore import Qt
from PySide6.QtWidgets import (
    QCheckBox,
    QDoubleSpinBox,
    QFormLayout,
    QHBoxLayout,
    QLineEdit,
    QScrollArea,
    QSpinBox,
    QTreeWidget,
    QTreeWidgetItem,
    QWidget,
)

from ..session import Session

_GROUPS = [
    ("Camera", "camera"),
    ("Turret", "turret"),
    ("Jet", "jet"),
    ("Detector", "detector"),
    ("Servo", "servo"),
    ("Mission", "mission"),
    ("Scenario", "scenario"),
]


class ModelEditor(QWidget):
    def __init__(self, session: Session, parent=None) -> None:
        super().__init__(parent)
        self.session = session
        self._widgets: dict[tuple[str, str], QWidget] = {}
        self._current_group: str | None = None

        layout = QHBoxLayout(self)
        self.tree = QTreeWidget()
        self.tree.setHeaderHidden(True)
        self.tree.setMaximumWidth(160)
        for label, key in _GROUPS:
            item = QTreeWidgetItem([label])
            item.setData(0, Qt.ItemDataRole.UserRole, key)
            self.tree.addTopLevelItem(item)
        layout.addWidget(self.tree)

        self._scroll = QScrollArea()
        self._scroll.setWidgetResizable(True)
        layout.addWidget(self._scroll, 1)

        self.tree.currentItemChanged.connect(self._on_select)
        self.session.changed.connect(self._refresh_values)
        self.select_group("jet")  # a sensible default landing group

    # -- public --------------------------------------------------------------

    def select_group(self, key: str) -> None:
        for i in range(self.tree.topLevelItemCount()):
            item = self.tree.topLevelItem(i)
            if item.data(0, Qt.ItemDataRole.UserRole) == key:
                self.tree.setCurrentItem(item)
                return

    # -- internals -----------------------------------------------------------

    def _group_obj(self, key: str):
        return self.session.scenario if key == "scenario" else getattr(self.session.config, key)

    def _on_select(self, cur, _prev) -> None:
        if cur is None:
            return
        self._current_group = cur.data(0, Qt.ItemDataRole.UserRole)
        self._build_panel(self._current_group)

    def _build_panel(self, key: str) -> None:
        obj = self._group_obj(key)
        panel = QWidget()
        form = QFormLayout(panel)
        self._widgets = {}
        for f in fields(obj):
            widget = self._make_widget(key, f.name, getattr(obj, f.name))
            form.addRow(f.name, widget)
        self._scroll.setWidget(panel)

    def _make_widget(self, group: str, name: str, value) -> QWidget:
        # bool must be checked before int (bool is an int subclass)
        if isinstance(value, bool):
            w = QCheckBox()
            w.setChecked(value)  # set before connecting -> no spurious edit
            w.toggled.connect(lambda v, n=name: self._edit(group, n, bool(v)))
        elif isinstance(value, int):
            w = QSpinBox()
            w.setRange(-1_000_000, 1_000_000)
            w.setValue(value)
            w.valueChanged.connect(lambda v, n=name: self._edit(group, n, int(v)))
        elif isinstance(value, float):
            w = QDoubleSpinBox()
            w.setRange(-1e6, 1e6)
            w.setDecimals(4)
            w.setValue(value)
            w.valueChanged.connect(lambda v, n=name: self._edit(group, n, float(v)))
        else:
            # tuples / None (extra_fires, decoy): read-only for now (P2 scenario editor)
            w = QLineEdit(repr(value))
            w.setReadOnly(True)
        self._widgets[(group, name)] = w
        return w

    def _edit(self, group: str, name: str, value) -> None:
        try:
            self.session.set_field(group, name, value)
        except ValueError:
            self._set_widget_value(self._widgets.get((group, name)),
                                   self.session.field(group, name))

    def _refresh_values(self) -> None:
        if self._current_group is None:
            return
        obj = self._group_obj(self._current_group)
        for f in fields(obj):
            w = self._widgets.get((self._current_group, f.name))
            if w is not None:
                self._set_widget_value(w, getattr(obj, f.name))

    def _set_widget_value(self, w, value) -> None:
        if w is None:
            return
        w.blockSignals(True)
        if isinstance(w, QCheckBox):
            w.setChecked(bool(value))
        elif isinstance(w, QSpinBox):
            w.setValue(int(value))
        elif isinstance(w, QDoubleSpinBox):
            w.setValue(float(value))
        elif isinstance(w, QLineEdit):
            w.setText(repr(value))
        w.blockSignals(False)
